### ISSUE TITLE
GPG signing could be optional

### ISSUE THREAD

**Issue by eiswind** [BestSolution-at/maven-osgi-plugin#11]
I wonder if the GPG signing could be moved to a profile, so that one could build it locally without GPG Keys.

If you agree, I could provide a pull request.

**Comment by lauritziu** [comment]
you can switch it off by 
-Dgpg.skip=true or -Dpgp dont remember exactly.

**Comment by eiswind** [comment]
That makes sense too :) I'll give it a try. Thx!
