### ISSUE TITLE
Wrong file URI's in generated config.ini for Windows

### ISSUE THREAD

**Issue by lauritziu** [BestSolution-at/maven-osgi-plugin#5]
We had a Problem starting up the equinox-framework in an environment configured with the Maven-OSGI-Plugin.

The startup failed only in Microsoft Windows. In an Mac OS environment everything worked fine.
But in Windows the configuration osgi-framework-path could not be resolved.
The problem was, that the config.ini file written by the MAVEN-OSGI-Plugin was not correctly readable by Equinox.

The Pathes were read as Properties and thus all backslashes were filtered us and pathes were all merged together ("C:usersmyusername.m2repository")
The config.ini is generated by the MVNBaseOSGILauchPlugin class of the MAVEN-OSGI-Plugin:
In these four locations pathes are put into the config.ini directly (path.toString()):

```
"reference\\:file:" + element.path.toString()
"osgi.install.area=file:" + p.getParent().resolve("install").toString()
"osgi.framework=file:" + equinox.get().path.toString()
"org.eclipse.equinox.simpleconfigurator.configUrl=file:"+ bundlesInfo.toAbsolutePath().toString()
```

We solved the problem this way: The pathes are all converted to URIs first, because URIs do not contain backslashes.
Then the four locations look like this:

```
"reference:" + element.path.toUri().toString()
"osgi.install.area=" + p.getParent().resolve("install").toUri().toString()
"osgi.framework=" + equinox.get().path.toUri().toString()
"org.eclipse.equinox.simpleconfigurator.configUrl="+ bundlesInfo.toAbsolutePath().toUri().toString()
```

With these changes the equinox-framework starts up without problems.

**Comment by tomsontom** [comment]
Right that makes sense, as I'm on OS-X I did not catch that problem!

**Comment by lauritziu** [comment]
We have some more modifications to the maven-osgi-plugins and a maven extension that makes it possible to build your  [maven-e4-sample-plugin](https://github.com/BestSolution-at/e4-efxclipse-maven-sample) completely in one maven reactor run. That was not possible before. Complete means: up to the product, that is startable. 

I'm about to make these changes available via a pull request. You are interested?

**Comment by tomsontom** [comment]
of course I'm happy to merge any PRs that improve the experience!

**Comment by tomsontom** [comment]
For documentation purpose: @lauritziu signed the ECA as lauritziu_ii@yahoo.de and has the right to contribute this code under EPL v1.0. @lauritziu can you please confirm this with "YES".
